config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'posts#index'

  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  resources :subscribers, only: [:create, :index] do
    get :unsubscribe, on: :member
  end
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    if user.admin?
      can :manage, :all
    else    
      can :read, Post
      can :manage, Post, user_id: user.id
      can :create, Comment
    end

  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post

  validates :text, presence: true
  validates :author, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :user
  has_many :comments, dependent: :delete_all

  validates :title, presence: true
  validates :body, presence: true
  validates :user, presence: true

  after_create :send_emails

  default_scope do
    order(id: :desc)
  end

  def send_emails
    PostMailer.post_mail(self).deliver_later
  end

end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
  has_secure_token :token

  validates :email, presence: true, uniqueness: true, email: true
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  def create
    @post = Post.friendly.find params[:post_id]
    @comment = @post.comments.build comment_params
    @comment.author = current_user.username if user_signed_in?
    if @comment.save
      redirect_to post_path(@post), notice: 'Comment added.'
    else
      render 'posts/show'
    end
  end

  def destroy
    comment = Comment.find params[:id]
    post_id = comment.post_id
    comment.destroy
    redirect_to post_path(post_id), notice: 'Comment deleted.'
  end

  private

  def comment_params
    params.require(:comment).permit(:author, :text)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  load_and_authorize_resource

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new post_params
    @post.user = current_user
    if @post.save
      redirect_to posts_path, notice: 'Post successfully created.'
    else
      render :new
    end
  end

  def edit
    @post = Post.friendly.find params[:id]
  end

  def update
    @post = Post.friendly.find params[:id]
    if @post.update_attributes post_params
      redirect_to posts_path, notice: 'Post saved.'
    else
      render :edit
    end
  end

  def destroy
    @post = Post.friendly.find params[:id]
    @post.destroy
    redirect_to posts_path, notice: 'Post deleted.'
  end

  def show
    @post = Post.friendly.find params[:id]
    @comment = @post.comments.build
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  load_and_authorize_resource only: :index

  def index
    @subscribers = Subscriber.all
  end

  def create
    @subscriber = Subscriber.new subscriber_params
    if @subscriber.save
      @message = "Email #{@subscriber.email} subsribed"
    else
      @message = "#{@subscriber.email} #{@subscriber.errors.messages.values.join(", ")}"
    end
  end

  def unsubscribe
    subscriber = Subscriber.find_by_token params[:id]
    if subscriber
      @email = subscriber.email
      subscriber.destroy
    end
  end

  private

  def subscriber_params
    params.require(:subscriber).permit(:email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def markdown(text)
    renderer = Redcarpet::Render::HTML.new(hard_wrap: true, filter_html: true)
    options = {
        autolink: true,
        no_intra_emphasis: true,
        fenced_code_blocks: true,
        lax_html_blocks: true,
        strikethrough: true,
        superscript: true,
        space_after_headers: true
    }
    Redcarpet::Markdown.new(renderer, options).render(text).html_safe
  end
  
end

app/views/comments/_comment.html.erb
<% unless comment.new_record? %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <b><%= comment.author %></b>
      <% if can? :manage, comment %>
        <div class="btn-group btn-group-sm btn-group-right" role="group">
          <%= link_to 'Delete', post_comment_path(comment.post_id, comment.id), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'  %>
        </div>
      <% end %>
    </div>
    <div class="panel-body">
      <%= comment.text %>
    </div>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= simple_form_for [@post, @comment] do |f| %>
  <%= f.input :author unless user_signed_in? %>
  <%= f.input :text %>
  <%= f.button :submit, 'Comment' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <title><%= content_for?(:title) ? yield(:title) : "Blog" %></title>
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
      <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.3.0/respond.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Blog', root_path, class: 'navbar-brand' %>
        </div>

        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <%= render 'shared/subscribe' %>
          <%= render 'shared/menu' %>
        </div>
      </div>
    </nav>

    <div id="main-container" class="container">
      <div class="row">
        <div class="col-md-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div>

      <footer>
        <p>&copy; <%= mail_to 'uncoder@gmail.com' %> 2015</p>
      </footer>

    </div>

  </body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
  <%= f.input :title %>
  <%= f.input :body, as: :pagedown, input_html: { preview: true } %>
  <%= f.button :submit, 'Save' %>
<% end %>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>
<br/>
<%= render 'form' %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>

  <div class="panel panel-default">
    <div class="panel-heading">
      <b><%= post.title %></b>
      <div class="btn-group btn-group-sm btn-group-right" role="group">
        <%= link_to 'read', post_path(post), class: 'btn btn-primary' %>
        <% if can? :manage, post %>
          <%= link_to 'Edit', edit_post_path(post), class: 'btn btn-info' %>
          <%= link_to 'Delete', post_path(post), class: 'btn btn-danger', method: :delete, data: { :confirm => 'Are you sure?' } %>
        <% end %>
      </div>
    </div>
    <div class="panel-body">
      <%= strip_tags(markdown(post.body)).truncate(300) %>
    </div>
  </div>

<% end %>

app/views/posts/new.html.erb
<h2>Create new Post</h2>
<br/>
<%= render 'form' %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<br/>
<p><%= markdown(@post.body) %></p>
<hr/>
<h3>Comments</h3>
<%= render 'comments/form' %>
<hr/>
<%= render partial: "comments/comment", collection: @post.comments %>

app/views/shared/_menu.html.erb
<ul class="nav navbar-nav navbar-right">
  <li>
    <%= link_to posts_path do  %>
      <span class="glyphicon glyphicon-th-list"></span>
      All posts
    <% end %>
  </li>
  <li>
    <%= link_to new_post_path do %>
      <span class="glyphicon glyphicon-pencil"></span>
      Write Post
    <% end %>
  </li>
  <% unless user_signed_in? %>
    <li>
      <%= link_to new_user_session_path do %>
        <span class="glyphicon glyphicon-user"></span>
        Sign In
      <% end %>
    </li>
  <% else %>
    <li>
      <%= link_to destroy_user_session_path, method: :delete do %>
        <span class="glyphicon glyphicon-user"></span>
        Sign Out
      <% end %>
    </li>
  <% end %>
  <% if can? :manage, :subscriber %>
    <li>
      <%= link_to subscribers_path do %>
        <span class="glyphicon glyphicon-envelope"></span>
        Subscribers
      <% end %>
    </li>
  <% end %>
</ul>

app/views/shared/_subscribe.html.erb
<%= simple_form_for :subscriber, url: subscribers_path, remote: true, html: { class: 'form-inline navbar-form navbar-left' } do |f| %>
  <%= f.input :email, label: false, placeholder: 'Your email' %>
  <%= f.button :submit, 'Subscribe', class: 'btn btn-defaul' %>
<% end %>

app/views/subscribers/create.js.erb
alert("<%= @message %>");
$('#subscriber_email').val('');

app/views/subscribers/index.html.erb
<% unless @subscribers.empty? %>
  <table class="table table-striped table-bordered">
    <tr>
      <th>Email</th>
      <th>Token</th>
      <th>Actions</th>
    </tr>
    <% @subscribers.each do |s| %>
      <tr>
        <td><%= s.email %></td>
        <td><%= s.token %></td>
        <td><%= link_to 'unsubscribe', unsubscribe_subscriber_path(s.token), class: 'btn btn-xs btn-danger' %></td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/subscribers/unsubscribe.html.erb
<h1>
  <% if @email %>
    <%= @email %> has been deleted from list
  <% else %>
    Invalid token.
  <% end %>
</h1>
<br/>